### ISSUE TITLE
Hello, I was wondering how this library drives subprocesses? I don't see any useful examples?

### ISSUE THREAD

**Issue by dengsong666** [vhidvz/workflow-js#4]
I am using nestjs and like it very much, but the documentation is too little and I am at a loss when dealing with complex problems, can you provide me with some help? Or other documentation references

**Comment by dengsong666** [comment]
I tried many times, but I couldn't start the subprocess. In my understanding, the sub-process is automatically executed when the main process is executed, but it is not, it is as if the process in the sub-process does not exist, is not supported? Because I use nestjs, I was just happy to see this open source library, and now I have a lot more worries, if someone can give me a little help, otherwise I have to give it up

**Comment by vhidvz** [comment]
Hi, dear @dengsong666 
Currently, this project does not support sub-processes. I plan to complete the documentation details next month with support for sub-processes. Currently, only tasks are supported among the BPMN2 activities.

**Comment by dengsong666** [comment]
> Hi, dear @dengsong666 Currently, this project does not support sub-processes. I plan to complete the documentation details next month with support for sub-processes. Currently, only tasks are supported among the BPMN2 activities.

ok, thanks for your response, improved documentation and support for subprocesses and more, great for nestjs users, this is the best node workflow engine project I've seen so far and I hope more and more people use it
